### ISSUE TITLE
关于放置画的交互动作

### ISSUE THREAD

**Issue by BackWheel** [AzureHanChen/EasyLobby#1]
我发现插件并没有一个选项可以调整玩家是否可以放置画，而当我安装这个插件后，所有世界都将无法放置画（我在config的Enablewold选项中只设置了一个世界启用）。

**Comment by AzureHanChen** [comment]
您好,我这里初步判断是EToEDamage选项控制的
我确实疏忽大意没有添加世界限制,下个版本会修复的,
并且必须是OP,且在创造模式下才能破坏
